package org.sunrise.dangdang.dao;

import org.apache.ibatis.annotations.Param;
import org.sunrise.dangdang.bean.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String id);

    /**
     *
     * @param email
     * @return
     */
    User selectByPrimaryEmail(String email);

    /**
     *
     * @param name
     * @return
     */
    User selectByPrimaryName(String name);

    /**
     *
     * @param name
     * @param pwd
     * @return
     */
    User selectByPrimaryNameAndPwd(@Param("name") String name, @Param("pwd") String pwd);

    /**
     *
     * @param email
     * @param pwd
     * @return
     */
    User selectByPrimaryEmailAndPwd(String email,String pwd);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);



}